apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mosp.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mosp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.db.size }}
{{- if .Values.persistence.logs.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mosp.fullname" . }}-logs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mosp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
{{- end }}
