{{- if not .Values.postgresql.existingSecret }}
{{- $name := printf "%s-db" (include "mosp.fullname" .) }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name }}
{{- $password := "" }}
{{- if $existing }}
{{- $password = index $existing.data .Values.postgresql.existingSecretKey }}
{{- else }}
{{- $password = randAlphaNum 24 | b64enc }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mosp.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.postgresql.existingSecretKey }}: {{ $password }}
{{- end }}
