apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mosp
  namespace: mosp
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: mydnschallenge
  routes:
    - match: Host(`mp.doany.io`)
      kind: Rule
      priority: 50
      services:
        - name: mosp
          port: 8080
